name: flutter_voice_processor
description: A Flutter audio recording plugin designed for real-time speech audio processing.
version: 1.1.0
homepage: https://picovoice.ai/
repository: https://github.com/Picovoice/flutter-voice-processor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ai.picovoice.flutter.voiceprocessor
        pluginClass: FlutterVoiceProcessorPlugin
      ios:
        pluginClass: FlutterVoiceProcessorPlugin