name: flutter_voice_processor
description: A Flutter package plugin for delivering microphone audio buffers to shared code.
version: 1.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ai.picovoice.flutter.voiceprocessor
        pluginClass: FlutterVoiceProcessorPlugin
      ios:
        pluginClass: FlutterVoiceProcessorPlugin