name: Flutter Example

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/flutter-example.yml'
      - 'example/**'
      - '!example/README.md'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - '.github/workflows/flutter-example.yml'
      - 'example/**'
      - '!example/README.md'

defaults:
  run:
    working-directory: example

jobs:
  build-android:
    name: Build Android demo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter-version: ['2.8.1', '3.0.4', '3.10.6']
        include:
        - flutter-version: 2.8.1
          gradle-version: 6.5
          agp-version: 4.1.3
          java-version: 11
        - flutter-version: 3.0.4
          gradle-version: 7.5
          agp-version: 7.4.2
          java-version: 11
        - flutter-version: 3.10.6
          gradle-version: 8.2
          agp-version: 8.2.2
          java-version: 17

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'

    - name: Install Flutter ${{ matrix.flutter-version }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ matrix.flutter-version }}

    - uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: ${{ matrix.gradle-version }}

    - name: Install dependencies
      run: flutter pub get

    - name: Generate gradle wrapper
      run: ./gradlew wrapper --gradle-version ${{ matrix.gradle-version }} --distribution-type all
      working-directory: example/android

    - name: Inject AGP version
      run: echo agpVersion="${{ matrix.agp-version }}" >> local.properties

    - name: Build
      run: flutter build apk

  # build-ios:
  #   name: Build iOS demo
  #   runs-on: macos-latest
  #   strategy:
  #     matrix:
  #       flutter-version: ['2.8.1', '3.0.4']

  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Install Flutter ${{ matrix.flutter-version }}
  #     uses: subosito/flutter-action@v2
  #     with:
  #       flutter-version: ${{ matrix.flutter-version }}
  #       architecture: x64

  #   - name: Update Cocoapods repo
  #     run: pod repo update

  #   - name: Install dependencies
  #     run: flutter pub get

  #   - name: Build
  #     run: flutter build ios --release --no-codesign
